FROM grafana/grafana

RUN grafana-cli plugins install ryantxu-ajax-panel 
RUN grafana-cli plugins install natel-plotly-panel
RUN grafana-cli plugins install bessler-pictureit-panel
RUN grafana-cli plugins install pr0ps-trackmap-panel
